create user SemiProject identified by DataBase12341234;

grant    connect, RESOURCE
      ,  create any table, update any TABLE
      ,  delete any table, insert any TABLE 
      TO SemiProject;  

alter user SemiProject quota 50m on users;

select * from ALL_USERS;

create table SIGNUP(
      PKID NUMBER
    , USERID VARCHAR2(50)
    , PASSWORD VARCHAR2(50)
    , USERNAME VARCHAR2(50)
    , PHONENUMBER VARCHAR(50)
    , EMAIL VARCHAR2(50)
    , SIGNDATE date DEFAULT SYSDATE
);

ALTER TABLE SIGNUP ADD CONSTRAINT PK_PKID PRIMARY KEY(PKID);
ALTER TABLE SIGNUP MODIFY USERID CONSTRAINT NN_USERID NOT NULL;
ALTER TABLE SIGNUP MODIFY PASSWORD CONSTRAINT NN_PASSWORD NOT NULL;
ALTER TABLE SIGNUP MODIFY USERNAME CONSTRAINT NN_USERNAME NOT NULL;
ALTER TABLE SIGNUP MODIFY PHONENUMBER CONSTRAINT NN_PHONENUMBER NOT NULL;
ALTER TABLE SIGNUP MODIFY EMAIL CONSTRAINT NN_EMAIL NOT NULL;

CREATE TABLE WRITER(
      ID NUMBER
    , PKID NUMBER
    , TITLE VARCHAR2(50)
    , CONTENTS VARCHAR2(2000)
    , PLACE VARCHAR(50)
    , PHONENUMBER VARCHAR2(15)
    , PHOTOPATH VARCHAR2(100)
    , WRITERDATE VARCHAR2(50)
);
alter table writer modify place varchar2(1000);
ALTER TABLE WRITER ADD CONSTRAINT PK_ID PRIMARY KEY(ID);
ALTER TABLE WRITER ADD CONSTRAINT FK_PKID FOREIGN KEY(PKID) REFERENCES SIGNUP(PKID);
ALTER TABLE WRITER MODIFY TITLE CONSTRAINT NN_TITLE NOT NULL;
ALTER TABLE WRITER MODIFY CONTENTS CONSTRAINT NN_CONTENTS NOT NULL;
ALTER TABLE WRITER MODIFY WRITERDATE DEFAULT TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS');

CREATE SEQUENCE SIGNUP_SEQ NOCACHE;
CREATE SEQUENCE WRITER_SEQ NOCACHE;

drop table writer;
drop table signup;

drop sequence signup_seq;
drop sequence writer_seq;


select * from USER_TAB_COLUMNS; where table_name ='signup';

SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'WRITER';
select * from signup;

INSERT INTO SIGNUP VALUES(SIGNUP_SEQ.NEXTVAL,'ADMIN','ADMIN1234','관리자','010-1234-1234','admin@naver.com',sysdate);
select * from signup;
INSERT INTO writer values(writer_seq.nextval,1,'안녕하세요
','테스트입니다.','장충동','010-7577-7575','/user/ijonghun',sysdate);
select * from writer;
SELECT * FROM SIGNUP WHERE USERID = 'ADMIN';
SELECT ID,SIGNUP.USERID ,TITLE, CONTENTS, PLACE, WRITER.PHONENUMBER, PHOTOPATH, )
FROM WRITER JOIN SIGNUP ON WRITER.PKID = SIGNUP.PKID;
UPDATE WRITER SET TITLE = '장재완', CONTENTS ='열이많음', PLACE = '강남역',
PHONENUMBER = '01010101' WHERE ID = '3';

SELECT * FROM(SELECT * FROM WRITER WHERE PKID = '1' ORDER BY ID) WHERE ROWNUM <= 6;

delete  from writer where id = '23';

