create user SemiProject identified by DataBase12341234;

grant    connect, RESOURCE
      ,  create any table, update any TABLE
      ,  delete any table, insert any TABLE 
      TO SemiProject;  

alter user SemiProject quota 50m on users;

select * from ALL_USERS;

create table SIGNUP(
      PKID NUMBER
    , USERID VARCHAR2(50)
    , PASSWORD VARCHAR2(50)
    , USERNAME VARCHAR2(50)
    , PHONENUMBER VARCHAR(50)
    , EMAIL VARCHAR2(50)
    , SIGNDATE date DEFAULT SYSDATE
);

ALTER TABLE SIGNUP ADD CONSTRAINT PK_PKID PRIMARY KEY(PKID);
ALTER TABLE SIGNUP MODIFY USERID CONSTRAINT NN_USERID NOT NULL;
ALTER TABLE SIGNUP MODIFY PASSWORD CONSTRAINT NN_PASSWORD NOT NULL;
ALTER TABLE SIGNUP MODIFY USERNAME CONSTRAINT NN_USERNAME NOT NULL;
ALTER TABLE SIGNUP MODIFY PHONENUMBER CONSTRAINT NN_PHONENUMBER NOT NULL;
ALTER TABLE SIGNUP MODIFY EMAIL CONSTRAINT NN_EMAIL NOT NULL;

CREATE TABLE WRITER(
      ID NUMBER
    , PKID NUMBER
    , TITLE VARCHAR2(50)
    , CONTENTS VARCHAR2(2000)
    , PLACE VARCHAR(50)
    , PHONENUMBER VARCHAR2(15)
    , PHOTOPATH VARCHAR2(100)
    , WRITERDATE DATE
);

ALTER TABLE WRITER ADD CONSTRAINT PK_ID PRIMARY KEY(ID);
ALTER TABLE WRITER ADD CONSTRAINT FK_PKID FOREIGN KEY(PKID) REFERENCES SIGNUP(PKID);
ALTER TABLE WRITER MODIFY TITLE CONSTRAINT NN_TITLE NOT NULL;
ALTER TABLE WRITER MODIFY CONTENTS CONSTRAINT NN_CONTENTS NOT NULL;
ALTER TABLE WRITER MODIFY(WRITERDATE DEFAULT SYSTIMESTAMP);

CREATE SEQUENCE SIGNUP_SEQ NOCACHE;
CREATE SEQUENCE WRITER_SEQ NOCACHE;


select * from USER_TAB_COLUMNS; where table_name ='signup';

SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'WRITER';
select * from signup;